# -*- coding: utf-8 -*-
"""Python Z to H - Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-x0QiabPSC4t3F7Zas_FL7VSGTCiaHn

Q.1. Write a program to find the prime number.
"""

n1 = int(input('Enter first number: '))
n2 = int(input('Enter second number: '))
print('Prime number between' + ' ' + str(n1) + ' ' + 'and' +' ' +str(n2))
for i in range(n1, n2+1):
  if i>1:
    for j in range(2,i):
        if(i % j==0):
            break
    else:
        print(i)

"""Q.2. Enter a number to program and get the output "Prime" or "Not Prime"."""

number = int(input("Enter any number: "))
if number > 1:
    for i in range(2, number):
        if (number % i) == 0:
            print("Not Prime")
            break
    else:
        print("Prime")

else:
    print("Not Prime")

