# -*- coding: utf-8 -*-
"""Python Z to H - Day 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wD03MR-SAqfd5F7gqOtrS69b2yqM7s-y

Q.1. Write a program to implement insertion sort.
"""

def insertion_sort(alist):
    for i in range(1, len(alist)):
        temp = alist[i]
        j = i - 1
        while (j >= 0 and temp < alist[j]):
            alist[j + 1] = alist[j]
            j = j - 1
        alist[j + 1] = temp
 
alist = input('Enter the list of numbers to implement insertion sort: ').split()
alist = [int(x) for x in alist]
insertion_sort(alist)
print('Sorted list: ', end='')
print(alist)