# -*- coding: utf-8 -*-
"""Python Z to H - Day1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aaRiPyCWTmOdZSX44BYCITVpAcsNU1oQ

**Day 1 Assignment**

Q.1. add two number
"""

num1 = input('Enter first number: ')
num2 = input('Enter second number: ')
sum = int(num1) + int(num2)
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

"""Q.2. Try to add integer with string and see the output"""

s = "The year is "
i = 2021
print (s+str(i))

"""Q.3. Print variable and strings in one line with the help of f string"""

f_name = "Akanksha"
l_name = "Kriti"
print(f"My first name is {f_name} and last name is {l_name}.")

"""Q.4. How to add space and new line in the print statement"""

a="Bread"
b="Butter"
print(a+ " " +b) #for adding space

print("Bread\nButter") #for new line

